# Generated by Django 2.2 on 2019-06-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Book_id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.FloatField()),
                ('Year', models.DateField()),
                ('edition', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Writer_name', models.CharField(max_length=50)),
                ('Book_name', models.CharField(max_length=50)),
                ('Book_type', models.IntegerField()),
                ('Book_category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Books_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bookstore_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookStore_name', models.CharField(max_length=50)),
                ('out_of_stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='secondhand_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='StoreBooks_of_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Bookstore_books')),
            ],
        ),
    ]
