# Generated by Django 2.2 on 2019-06-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebooks_of_user',
            name='newuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secondhand_books',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
        migrations.AddField(
            model_name='bookstore_books',
            name='Book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
        migrations.AddField(
            model_name='bookstore_books',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.BookStore'),
        ),
        migrations.AddField(
            model_name='books_of_user',
            name='secondbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.secondhand_books'),
        ),
        migrations.AddField(
            model_name='books_of_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
