# Generated by Django 2.2 on 2019-06-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='u_id',
            field=models.CharField(max_length=500),
        ),
    ]
