# Generated by Django 2.2 on 2019-06-06 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('bookstore_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=1000)),
                ('bstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.BookStore')),
            ],
        ),
    ]
