# Generated by Django 2.2 on 2019-06-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer1',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(max_length=1000)),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=1000)),
                ('Writer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.Writer1')),
            ],
        ),
    ]
